import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 * - use keyboard shortcuts to navigate through the sidebar
 * - hide/show the sidebar (responsive layout)
 * - customize the sidebar's appearance with CSS
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [
    "learn/intro",
    "learn/installation",
    "learn/your-first-agent",

    {
      type: "category",
      label: "Fundamentals",
      items: [
        "learn/fundamentals/what-is-agent-forge",
        "learn/fundamentals/decorator-pattern",
        "learn/fundamentals/llm-providers",
      ],
    },

    {
      type: "category",
      label: "Agents",
      items: ["learn/agents/agent-basics"],
    },

    {
      type: "category",
      label: "Tools",
      items: ["learn/tools/adding-tools"],
    },

    {
      type: "category",
      label: "Teams",
      items: ["learn/teams/team-basics"],
    },

    {
      type: "category",
      label: "Advanced",
      items: [
        "learn/advanced/rag-integration",
        "learn/advanced/distributed-agents",
        "learn/advanced/streaming",
        "learn/advanced/plugins",
      ],
    },
  ],

  // API Reference Sidebar
  apiSidebar: [
    {
      type: "doc",
      id: "api-reference/api-reference", // Overview page
    },
    {
      type: "category",
      label: "Core Classes",
      items: [
        "api-reference/core-classes/agent",
        "api-reference/core-classes/agent-forge",
        "api-reference/core-classes/team",
        "api-reference/core-classes/workflow",
        "api-reference/core-classes/llm",
      ],
    },
    {
      type: "category",
      label: "Decorators",
      items: [
        "api-reference/decorators/index",
        "api-reference/decorators/core-decorators",
        "api-reference/decorators/tool-decorators",
        "api-reference/decorators/a2a-decorators",
        "api-reference/decorators/rag-decorators",
        "api-reference/decorators/utility-decorators",
        "api-reference/decorators/plugin-decorators",
      ],
    },
    {
      type: "category",
      label: "Utilities",
      items: [
        "api-reference/utilities/index",
        "api-reference/utilities/rate-limiter",
        "api-reference/utilities/event-emitter",
        "api-reference/utilities/streaming",
      ],
    },
  ],

  // Examples Sidebar
  examplesSidebar: [
    {
      type: "autogenerated",
      dirName: "examples",
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
