import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create two separate sidebars
  learnSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: ["learn/intro", "learn/installation", "learn/your-first-agent"],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "learn/core-concepts/yaml-defined-agents",
        "learn/core-concepts/tools-ecosystem",
        "learn/core-concepts/execution-patterns",
        "learn/core-concepts/llm-integration",
      ],
    },
    {
      type: "category",
      label: "Advanced Topics",
      items: [
        "learn/advanced/rate-limiting",
        "learn/advanced/debugging-features",
        "learn/advanced/streaming-support",
        "learn/advanced/model-context-protocol",
      ],
    },
    // Add more categories and docs for the "Learn" section here
    // {
    //   type: 'category',
    //   label: 'Core Concepts',
    //   items: ['learn/core-concept-1', 'learn/core-concept-2'],
    // },
  ],
  referenceSidebar: [
    "reference/intro",
    {
      type: "category",
      label: "Core",
      link: { type: "doc", id: "reference/core/index" },
      items: [
        "reference/core/agent",
        "reference/core/agent-forge",
        "reference/core/team",
        "reference/core/workflow",
      ],
    },
    {
      type: "category",
      label: "LLM",
      link: { type: "doc", id: "reference/llm/index" },
      items: [
        "reference/llm/llm-class",
        // Add specific LLM docs here
      ],
    },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "reference/tools/index" },
      items: [
        "reference/tools/tool",
        "reference/tools/tool-registry",
        "reference/tools/web-search-tool",
        "reference/tools/web-page-content-tool",
        "reference/tools/sec-api-tool",
        "reference/tools/mcp-tool",
      ],
    },
    {
      type: "category",
      label: "Utils",
      link: { type: "doc", id: "reference/utils/index" },
      items: [
        "reference/utils/event-emitter",
        "reference/utils/rate-limiter",
        "reference/utils/streaming",
      ],
    },
    {
      type: "category",
      label: "Types",
      link: { type: "doc", id: "reference/types/index" },
      items: [
        "reference/types/core-types",
        "reference/types/communication-types",
      ],
    },
  ],
};

export default sidebars;
